import type { ServerNode } from "./type";

export const MOCK_NODES: ServerNode[] = [
  {
    id: "vps-de-1",
    name: "Frankfurn-Core",
    ip: "194.87.12.44",
    provider: "Hetzner",
    location: "Germany",
    status: "online",
    metrics: {
      cpuUsage: 18,
      ramUsage: 42,
      networkSpeed: 120,
      diskUsage: 32,
      uptime: "99.98%",
      ping: 35,
      bandWithUp: 12.1,
      bandWithDown: 45.1,
    },
    lastSeen: new Date().toISOString(),
  },
  {
    id: "vps-fi-2",
    name: "Helsinki-Gateway",
    ip: "95.216.88.102",
    provider: "Hetzner",
    location: "Finland",
    status: "online",
    metrics: {
      cpuUsage: 89,
      ramUsage: 78,
      networkSpeed: 450,
      diskUsage: 68,
      uptime: "98.72%",
      ping: 18,
      bandWithUp: 88.0,
      bandWithDown: 120.5,
    },
    lastSeen: new Date().toDateString(),
  },
  {
    id: "vps-nl-3",
    name: "Amsterdam-Edge",
    ip: "185.220.101.5",
    provider: "DigitalOcean",
    location: "Netherlands",
    status: "offline",
    metrics: {
      cpuUsage: 0,
      ramUsage: 0,
      networkSpeed: 0,
      diskUsage: 0,
      uptime: "0%",
      ping: 0,
      bandWithUp: 0,
      bandWithDown: 0,
    },
    lastSeen: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
];
